[package]
edition = "2021"
name = "cimpl-reference"
version = "0.3.2"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]
name = "value_converter"

[features]
default = ["ffi"]
ffi = []

[dependencies]
cimpl = { path = "../..", optional = false }
thiserror = "2.0"

[build-dependencies]
cbindgen = "0.27"
