[package]
edition = "2021"
name = "uuid_ffi"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "uuid_ffi"

[features]
default = ["ffi"]
ffi = []

[dependencies]
cimpl = { path = "../.." }
thiserror = "2.0"
uuid = { version = "1.11", features = ["v4"] }

[build-dependencies]
cbindgen = "0.27"
